// GUIDEBOX ACTION
export const SET_GUIDEBOX_POS = "SET_GUIDEBOX_POS";
export const MOVE_GUIDEBOX = "MOVE_GUIDEBOX";
export const SET_GUIDEBOX_SHOW = "SET_GUIDEBOX_SHOW";

// ITEM ACTION
export const SET_SELECT_ITEM = "SET_SELECT_ITEM";
export const ADD_ITEM_IN_CONTENT = "ADD_ITEM_IN_CONTENT";
export const MOVE_ITEM_POS = "MOVE_ITEM_POS";


